### ISSUE TITLE
feature-request: use new `--video-crop` for cropping operations

### ISSUE THREAD

**Issue by dyphire** [Ashyni/mpv-scripts#21]
Ref: https://github.com/mpv-player/mpv/pull/12246
This will optimize performance and fix #19 

Note that this does not bring hwdec support.

**Comment by Ashyni** [comment]
Hello,

I started to do some test with `video-crop`, every crop change looks smoother than `lavfi-crop`, i will implement it properly, your PR miss multiple stuff, thanks for your contribution anyway.

Has for #19, this issue is related to `cropdetect` filter chain and not `crop`, so it doesn't change anything.
And it's partially fixed with `read_ahead_mode=0` (disable) in https://github.com/Ashyni/mpv-scripts/commit/72467235d3cafdc69b68c557397714ea90eefa0d and actually fully fixed with `read_ahead_mode=1/2` (enable) by [patch/ffmpeg/0001-avfilter-add-vf_dummysync.patch](https://github.com/Ashyni/mpv-scripts/blob/master/patch/ffmpeg/0001-avfilter-add-vf_dummysync.patch) which need to be discussed with ffmpeg dev.

For now, the script remains limited to soft decoding or `hwdec=*-copy`.
